### ISSUE TITLE
Installing .debs is impossible

### ISSUE THREAD

**Issue by mull0r** [ubuntu/app-center#1713] opened 2024-06-22 09:44 UTC
If I download a .deb for let's say discord --> there's an update, I need to download the deb-file. Why can't I install it with the GUI. Yes, I know the command line. I can manage it. But it isn't as user friendly as opening the .deb file with App Center and installing it using the GUI. This should be fixed for Ubuntu to become more user friendly.

**Comment by BLKKKBVSIK** [comment] 2024-06-24 06:47
Duplicate of #1407

**Closed by BLKKKBVSIK** 2024-06-24 06:47 UTC
