### ISSUE TITLE
Shrinked dd menus

### ISSUE THREAD

**Issue by fthx** [ubuntu/app-center#1483] opened 2023-11-07 07:12 UTC
Nvidia/Wayland 545.29:
![image](https://github.com/ubuntu/app-center/assets/23138504/b48bbe94-42b7-467e-bfdc-9c594d161034)
Happens with all menus.

I cannot test this in X11 since app does not start (cf. other bug).

**Comment by d-loose** [comment] 2023-11-07 07:24
Duplicate of #1473

**Closed by d-loose** 2023-11-07 07:24 UTC
