### ISSUE TITLE
As a user I want to see which applications I already have installed when browsing

### ISSUE THREAD

**Issue by local-optimum** [ubuntu/app-center#1427] opened 2023-10-02 08:11 UTC
Currently there is no indication of which apps I already have installed when searching for apps or browsing categories or the explore page, it would be good to have some kind of indicator (for example a check mark in the top right or equivalent) for applications that are already installed on my machine so it's easy to spot.

**Comment by d-loose** [comment] 2023-10-04 07:47
Duplicate of #1424

**Closed by d-loose** 2023-10-04 07:47 UTC
Labels: UI/UX
