### ISSUE TITLE
Window controls are in the wrong location

### ISSUE THREAD

**Issue by vadi2** [ubuntu/app-center#1808] opened 2024-09-04 12:26 UTC
Using App center 1.0.0, the window controls are on the right whereas they should be on the left per my configuration:

![Screenshot from 2024-09-04 14-26-26](https://github.com/user-attachments/assets/af72e220-557a-4003-900e-23409c3ae3d0)

**Comment by d-loose** [comment] 2024-09-04 12:30
Duplicate of #1666

**Closed by d-loose** 2024-09-04 12:30 UTC
