### ISSUE TITLE
Titlebar Buttons placement doesn't follow the configuration

### ISSUE THREAD

**Issue by hurelhuyag** [ubuntu/app-center#1480] opened 2023-11-03 11:06 UTC
![Screenshot from 2023-11-03 19-04-35](https://github.com/ubuntu/app-center/assets/1059242/c2ea7a51-8965-49f9-b6cf-4ee988c64672)

**Comment by d-loose** [comment] 2023-11-08 14:28
Duplicate of #1469.

Would need some work in https://github.com/ubuntu/yaru_widgets.dart and https://github.com/ubuntu/yaru.dart
@Jupi007 @Feichtmeier are there any plans in that direction?

**Closed by d-loose** 2023-11-08 14:28 UTC

**Comment by Feichtmeier** [comment] 2023-11-08 15:42
> Duplicate of #1469.
> 
> Would need some work in https://github.com/ubuntu/yaru_widgets.dart and https://github.com/ubuntu/yaru.dart
> @Jupi007 @Feichtmeier are there any plans in that direction?

Yes there is even a pull request by @12people however I don't feel competent enough to review this
Could you eventually review this @d-loose ?
