### ISSUE TITLE
Contributing to the app

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/app-center#1430] opened 2023-10-02 17:07 UTC
How to build this app from source and make some contributions to it?

**Comment by FussuChalice** [comment] 2023-10-04 07:03
1. Install Ubuntu Desktop.
2. To ubuntu download flutter (3.10.6) for this project and Dart SDK.
3. To ubuntu install Visual Studio Code. 
4. For VSCode install extenstions (flutter and dart).
5. Use ```git clone``` or another way for download project from github.
6. Extract project.
7. Go to project directory and start terminal there.
8. Run ```flutter doctor``` <- this command show what you must install. 
9. Run command in terminal ```flutter pub get```
10. Now you added dependencies to your project. 
11. Go to VSCode and Select Run -> Without debaging / with debaging. 

This short instruction was created for those who already have skills in writing flutter apps.

For more information go to official flutter website.

**Comment by anorld-droid** [comment] 2023-10-05 11:53
There is a dependency issue whenever `flutter pub get` is run, 
![image](https://github.com/ubuntu/app-center/assets/61829388/3a641f40-f5a6-47b7-be8c-bcbf9241a6d9)

**Comment by d-loose** [comment] 2023-10-05 12:06
Please make sure you're using Flutter 3.10.6.

We're preparing an updated README and a contribution guide in #1436

**Comment by soumyaDghosh** [comment] 2023-10-05 12:11
> There is a dependency issue whenever `flutter pub get` is run, ![image](https://user-images.githubusercontent.com/61829388/272893242-3a641f40-f5a6-47b7-be8c-bcbf9241a6d9.png)

Same error with me, but even with flutter version `3.10.6`. I downgraded my flutter and got to this version though.

**Comment by d-loose** [comment] 2023-10-05 14:04
#1436 got merged - there's a CONTRIBUTING.md now \o/

> Same error with me, but even with flutter version `3.10.6`. I downgraded my flutter and got to this version though.
Please double check that you're using the correct version and that your repository is clean - I can't reproduce any problems with 3.10.6.

**Closed by d-loose** 2023-10-05 14:04 UTC
