### ISSUE TITLE
snap-store showing updates while there is no update

### ISSUE THREAD

**Issue by alculete** [ubuntu/app-center#1216] opened 2023-04-11 17:32 UTC
![image](https://user-images.githubusercontent.com/2129497/231245279-0e19480c-c6c0-4c39-8e18-3eeebe4a434a.png)

**Comment by d-loose** [comment] 2023-05-30 12:21
We had a similar issue (#1062) before, but this was due to some client-side logic that was used to determine which snaps have updates. We've solved this by getting the list of updateable snaps directly from snapd, so there shouldn't be any difference now.

If you can reproduce the issue, could you please post the output of
```sh
curl -s --unix-socket /var/run/snapd.socket "http://localhost/v2/find?select=refresh"
```
Thanks!

**Comment by Feichtmeier** [comment] 2023-05-30 12:40
On a sidenote we should separate the list of installed snaps and the list of updates better. I try to make a fix for this tonight. It won't solve this issue but it could improve the speed of this page

**Comment by alculete** [comment] 2023-06-02 14:11
I noticed that the list now shows exactly the right snaps if you click update while the apps are open nothing will happen and no notification is given. tried snap changes on the terminal to see if was upgrading in the background and nothing was happening, had to close the app and manually update.
It should download the app and then asks the users to close to update, not allowing the user to open until is done. and show a notification after concluding saying the user can use the app now.

**Comment by d-loose** [comment] 2023-06-02 15:07
I'm not exactly sure if snapd automatically sends a desktop notification if we trigger a refresh of a snap that's currently running, or if we get an error status. In the latter case, we should make sure to communicate this to the user ourselves.
I'll look into it after the weekend! :)

**Comment by d-loose** [comment] 2023-09-26 08:39
I haven't experienced this issue in the app-center so far. Please re-open if someone notices it again!

**Closed by d-loose** 2023-09-26 08:39 UTC
Labels: bug, snap, prio: medium
