### ISSUE TITLE
SnapdException(kind: null,message many requests) error

### ISSUE THREAD

**Issue by kaunghtetmaung** [ubuntu/app-center#1711] opened 2024-06-20 14:49 UTC
[Screencast from 2024-06-20 21-17-29.webm](https://github.com/ubuntu/app-center/assets/146847618/c6f9a187-e4a2-41f7-b8c1-1a7572979271)

**Comment by d-loose** [comment] 2024-06-20 15:16
Duplicate of #1684

**Closed by d-loose** 2024-06-20 15:16 UTC
