### ISSUE TITLE
Debian's packages which installed are not visible in Manage of ubuntu Software 

### ISSUE THREAD

**Issue by flo42330** [ubuntu/app-center#1645] opened 2024-04-19 05:55 UTC
Hello,

In the Ubuntu application center, the Debian's packages which installed on the OS are not visible in the section "manage". 

for example, if you want uninstall an application, you can't find this application in "manage ". You must look for in the search bar the application, select deb. package and uninstall from this page.

It's not very intuitive.

Have a good day.

P.S. : sorry for the English mistakes, I'm French...

**Comment by d-loose** [comment] 2024-04-19 09:17
Duplicate of #1641

**Closed by d-loose** 2024-04-19 09:17 UTC
