### ISSUE TITLE
Application list is not complete

### ISSUE THREAD

**Issue by Antoine-H** [ubuntu/app-center#1809] opened 2024-09-04 21:04 UTC
I am using Ubuntu 24.04.1 LTS. App Center says "version 1.0.0". I would like to get a list of all installed app so I can chose which one I would like to remove.

I went to the "Manage" tab on the bottom left of the window ("Gérer" in the screenshot below), but I do not see all my apps in this list. I installed vim, but cannot see it there.

![image](https://github.com/user-attachments/assets/ad88c044-4eb3-429e-80cf-56457e9c9946)

I wanted to see a list like I used to get in previous releases of Ubuntu like:

![9OAhdai](https://github.com/user-attachments/assets/8736ce79-978b-4e06-aefd-2f5776d9d5f1)

**Comment by frankhuurman** [comment] 2024-09-05 09:40
For me it says this instead of just `Gérer` or `Manage`:
![image](https://github.com/user-attachments/assets/a5a33e94-e124-461f-bf8e-a1b456854816)

So maybe App Center is only used to manage Snap packages? which would be weird but explains why vim isn't showing if you installed it as a .deb.

**Comment by d-loose** [comment] 2024-09-05 09:55
Yes, that's correct - currently the "Manage" page only supports managing installed snaps.
Duplicate of #1641

**Closed by d-loose** 2024-09-05 09:55 UTC
