### ISSUE TITLE
Installed status in search results?

### ISSUE THREAD

**Issue by fthx** [ubuntu/app-center#1316] opened 2023-08-05 20:33 UTC
Hi all,

When I search for - let's say ^^ - Open Printing author apps, I get some results but in this tiles there is no info about installed-or-not status.

An icon or a text label would be welcome IMO.  :-)

[version 0.3.0]

**Comment by anasereijo** [comment] 2024-08-16 10:47
duplicate of https://github.com/ubuntu/app-center/issues/1424

**Closed by anasereijo** 2024-08-16 10:47 UTC
Labels: prio: low, feature request, UI/UX
