### ISSUE TITLE
FEAT: While runnng project on local system i'm getting "fatal error: 'cairo/cairo.h' file not found" Error #1460

### ISSUE THREAD

**Issue by Cevedale** [ubuntu/app-center#1516] opened 2023-12-05 09:51 UTC
you should install Cairo on your Ubuntu system:
sudo apt-get install libcairo2-dev

verify that your Flutter project has the correct dependencies specified in the 'pubspec.yaml' file.
dependencies:
cairo: ^0.9.0

update Flutter and FVM

**Comment by BLKKKBVSIK** [comment] 2023-12-12 10:09
Duplicate of #1460

**Closed by BLKKKBVSIK** 2023-12-12 10:09 UTC
