### ISSUE TITLE
must have a permission option for each snap app

### ISSUE THREAD

**Issue by neofeo** [ubuntu/app-center#1633] opened 2024-03-30 20:41 UTC
report from ubuntu noble. I just had to connect ppsspp emulator on to removable-media just to acomplish such task, it must be offered as option on installation or from the app store itself

**Comment by Recydywa** [comment] 2024-04-02 10:04
Yes it must offer a graphical interface for permissions.

At one point the Ubuntu Software had such graphical configuration for snaps. Or maybe it was in the Gnome Control Center but such thing should be independent from any desktop dependent program.

I use Unity and there isn't Gnome Control Center here and others will use KDE, Xfce, Mate or something else.

**Comment by AsciiWolf** [comment] 2024-04-11 20:52
Isn't this available directly in the Settings app?

**Comment by d-loose** [comment] 2024-04-30 13:09
Duplicate of #1356

**Closed by d-loose** 2024-04-30 13:09 UTC
