### ISSUE TITLE
Difficulty installing snap node

### ISSUE THREAD

**Issue by albertescanes** [ubuntu/app-center#1459] opened 2023-10-13 10:12 UTC
Hello there,

I am experiencing issues with finding Node (in Snap format) in the new App Center. I've tried various search queries and checked the "Development" section, but Node does not appear.
![image](https://github.com/ubuntu/app-center/assets/132266745/9e6cbac1-8bc4-4df9-ba4a-4c5202c69e34)
The only way I've managed to install it is by visiting the Snapcraft website (https://snapcraft.io/node) and clicking the green "Install" button. However, when I do this, the App Center opens the application, but it defaults to version 10/stable instead of the latest LTS 18.18.0 (as it used to in the old Software Center) or the latest stable version 20.8.0.
![image](https://github.com/ubuntu/app-center/assets/132266745/20d5097c-81c9-43de-91e6-81daa358340c)

Thank you for your support.

**Comment by BLKKKBVSIK** [comment] 2023-11-29 08:57
Duplicate of #1503

**Comment by matthew-hagemann** [comment] 2023-11-29 09:19
Hi @albertescanes, thank you for reporting this!

The issue of search results from snapcraft.io not matching the App Center is due to a `--wide` search flag not being set in our snapd client we are using in the App Center. `snap find` also makes use of a wide search, so you'll see the node snap appear in `snap find node` as well. I have created an [issue](https://github.com/canonical/snapd.dart/issues/98) upstream in the client to change this so that search results are consistent. 

Regarding the drop down, 20/stable is in there right at the bottom and after some scrolling, but it would definitely be improved to appear at the top of the list and as the default selected channel. We'll use the upstream issue to track the search results, and this issue to track the drop down ordering / default selection.

**Closed** 2024-09-16 09:20 UTC
Labels: enhancement: UI 👩‍🎨, difficulty: easy, prio: low
